name: Downgrade

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'paper/**'
      - '.gitignore'
  workflow_dispatch:

# Cancel redundant CI tests automatically
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  downgrade_test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Downgrade ${{ matrix.os }} - Julia ${{ matrix.version }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10' # current lts
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - run: julia -e 'using InteractiveUtils; versioninfo(verbose=true)'
      - uses: julia-actions/cache@v2
      - uses: JoshuaLampert/julia-downgrade-compat@11e35582d0098d2079cd6801bec5ec9decc50208
        with:
          skip: LinearAlgebra,SparseArrays,Statistics,Test
          projects: ., test
          mode: forcedeps
      - name: Run tests
        run: |
          julia --project=test --color=yes -e '
            import Pkg
            Pkg.develop(Pkg.PackageSpec(path=pwd()))
            Pkg.instantiate()
            Pkg.status()
            include("test/runtests.jl")
          '
